
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sahabt
 */
public class Stok extends javax.swing.JFrame {

    /**
     * Creates new form Stok
     */
    public Stok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUrunIsmi = new javax.swing.JTextField();
        cbKategori = new javax.swing.JComboBox<>();
        tfFiyat = new javax.swing.JTextField();
        mesajYazisi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urunTablosu = new javax.swing.JTable();
        ekleButonu = new javax.swing.JButton();
        guncelleButonu = new javax.swing.JButton();
        silButonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ürün ismi:");

        jLabel2.setText("Kategori:");

        jLabel3.setText("Fiyat:");

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kültür-Sanat", "Yemek", "Elekronik" }));

        mesajYazisi.setForeground(new java.awt.Color(153, 51, 0));

        urunTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UrunIsmi", "Kategori", "Fiyat"
            }
        ));
        urunTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urunTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urunTablosu);

        ekleButonu.setText("Ürün Ekle");
        ekleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButonuActionPerformed(evt);
            }
        });

        guncelleButonu.setText("Ürün Güncelle");
        guncelleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleButonuActionPerformed(evt);
            }
        });

        silButonu.setText("Ürün Sil");
        silButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silButonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mesajYazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfUrunIsmi)
                                    .addComponent(cbKategori, 0, 160, Short.MAX_VALUE)
                                    .addComponent(tfFiyat))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guncelleButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ekleButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(silButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfUrunIsmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekleButonu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelleButonu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(silButonu)))
                .addGap(50, 50, 50)
                .addComponent(mesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButonuActionPerformed
        mesajYazisi.setText("");
        DefaultTableModel model = (DefaultTableModel) urunTablosu.getModel();

        if (tfUrunIsmi.getText().trim().equals("")) {
            mesajYazisi.setText("Ürün ismi alani boş bırakılamaz..");
        } else {
            Object[] eklenecek = {tfUrunIsmi.getText(), cbKategori.getSelectedItem().toString(), tfFiyat.getText()};

            model.addRow(eklenecek);
        }
    }//GEN-LAST:event_ekleButonuActionPerformed

    private void guncelleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleButonuActionPerformed
        mesajYazisi.setText("");
        DefaultTableModel model = (DefaultTableModel) urunTablosu.getModel();
        int seciliRow = urunTablosu.getSelectedRow();
        if (seciliRow == -1) {
            if (urunTablosu.getRowCount() == 0) {
                mesajYazisi.setText("Urun tablosu su anda bos..");
            } else {
                mesajYazisi.setText("Lutfen guncellenecek urunu seciniz.. ");
            }
        } else {
            model.setValueAt(tfUrunIsmi.getText(), seciliRow, 0);
            model.setValueAt(cbKategori.getSelectedItem().toString(), seciliRow, 1);
            model.setValueAt(tfFiyat.getText(), seciliRow, 2);
            mesajYazisi.setText("Urun basariyla guncellendi..");
        }
    }//GEN-LAST:event_guncelleButonuActionPerformed

    private void urunTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urunTablosuMouseClicked
        DefaultTableModel model = (DefaultTableModel) urunTablosu.getModel();
        int seciliRow = urunTablosu.getSelectedRow();
        tfUrunIsmi.setText(model.getValueAt(seciliRow, 0).toString());
        cbKategori.setSelectedItem(model.getValueAt(seciliRow, 1).toString());
        tfFiyat.setText(model.getValueAt(seciliRow, 2).toString());
    }//GEN-LAST:event_urunTablosuMouseClicked

    private void silButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silButonuActionPerformed
        mesajYazisi.setText("");
        DefaultTableModel model = (DefaultTableModel) urunTablosu.getModel();
        int seciliRow = urunTablosu.getSelectedRow();
        if (seciliRow == -1) {
            if (urunTablosu.getRowCount() == 0) {
                mesajYazisi.setText("Urun tablosu su anda bos..");
            } else {
                mesajYazisi.setText("Lutfen silinecek urunu seciniz.. ");
            }
        } else {
            model.removeRow(seciliRow);
            mesajYazisi.setText("Urun basariyla silindi..");
        }
    }//GEN-LAST:event_silButonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JButton ekleButonu;
    private javax.swing.JButton guncelleButonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesajYazisi;
    private javax.swing.JButton silButonu;
    private javax.swing.JTextField tfFiyat;
    private javax.swing.JTextField tfUrunIsmi;
    private javax.swing.JTable urunTablosu;
    // End of variables declaration//GEN-END:variables
}
